# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    origin_prometheus: aio

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']

  - job_name: 'local-node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'caadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  # - job_name: 'jf91portfolioapi'
  #   static_configs:
  #   - targets: ['192.168.1.91:9191']
  #   metrics_path: /metrics-text
  
  - job_name: 'file_discovery'
    file_sd_configs:
    - files:
      - targets.json
  #  metrics_path: /metrics-text

